# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'RangeControlExample' do
  use_frameworks!
  pod 'RangeControl'
end

