# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/AlexeyIS/RCPodSpecs.git'


target 'RangeControlExample' do
  use_frameworks!
  pod 'RangeControl'
end

